### PR TITLE
Support NVME volumes

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@eherot this is pretty fancy. Are you using instances w/ NVME volumes?

**Comment by eherot** [comment]
We're exploring putting ES on them because they're way more storage for less money.

**Comment by jeffbyrnes** [comment]
Cool. They definitely look like better bang-for-the-buck, for a storage + speed combo.

**Comment by eherot** [comment]
yeah like 10x better, and 5x for speed. Leaves me wondering what the catch is.

**Comment by jeffbyrnes** [comment]
@eherot just in case you didn’t see it, there’s [this bug about I/O](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1668129/comments/29) that should be fixed by now.

**Comment by eherot** [comment]
Yikes. Thanks for pointing that out.

**Pull request merged**
